spring:
  profiles:
    active: 
    - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: miscroservicecloud-config-atcj-dev
---
spring:
  profiles: test #测试环境
  application:
    name: miscroservicecloud-config-atcj-test